### ISSUE TITLE
I'm not an Azure AD admin but wanna get data from ratecard!

### ISSUE THREAD

**Issue by SychevIgor** [Azure-Samples/billing-dotnet-ratecard-api#1]
Hello,
I'm a Field Engineer from Microsoft.
This API is looks cool, but I looks like can't use it for my subscriptions. I'm in microsoft.onwindows.com domain and I'm definitely not admin of this tenant. 
I did all steps from the guide https://github.com/Azure-Samples/billing-dotnet-ratecard-api/ but I have issue in after line 89  
 var result = authenticationContext.AcquireToken(String.Format("{0}/",ConfigurationManager.AppSettings["ARMBillingServiceURL"]),
                                                            ConfigurationManager.AppSettings["ClientID"],
                                                            new Uri(ConfigurationManager.AppSettings["ADALRedirectURL"]));
Login Dialog shows me  
AADSTS90093: Calling principal cannot consent due to lack of permissions. 

<b>Please, make your API simpler and without access to Azure AD. I know that it could be hard or bad designed, but peoples without administrative privileges need an access to this API</b>

**Comment by HarvestingClouds** [comment]
@SychevIgor were you able to connect or are you still having the issue. It definitely seems you have permissions issue with the account you are using. One way to check is by trying to login into the classic Azure portal using the account you are trying in the dialogue and navigate to Azure AD. Check if your user has the access to add an application in the Application tab. If not then you need to grant appropriate access. 
Also there are other ways to authenticate, e.g. using username and password or using certificates. I will provide samples for those authentication methods soon. Keep checking the pull requests.

**Comment by SychevIgor** [comment]
Hi, @20aman 
Yes, I can add an app on a classic portal. All steps were done.

**Comment by moinak3** [comment]
@SychevIgor - could you please reach out to me on mobandyo@microsoft.com, and we can chat about how to get you unblocked?
